### ISSUE TITLE
Jus 设置动态虚拟目录的时候，如果路径结尾没有斜杠（\）会在访问时报错。

### ISSUE THREAD

**Issue by yeahpop** [uucckk/AIroot-JUS#17]
```linux
2019/03/02 17:08:50 http: panic serving 10.110.10.55:23167: runtime error: invalid memory address or nil pointer dereference
goroutine 257 [running]:
net/http.(*conn).serve.func1(0x10cf0000)
        D:/go/src/net/http/server.go:1697 +0x9f
panic(0x668be0, 0x81a838)
        D:/go/src/runtime/panic.go:491 +0x1d0
jus/cn/airoot/util.(*JusServer).hasUrl(0x10e1c000, 0x10ef6000, 0x7f1300, 0x10d1a090, 0x10e0c000, 0x0)
        E:/GitHub/AIroot-JUS/src/jus/cn/airoot/util/server.go:1142 +0x167
jus/cn/airoot/util.(*JusServer).root(0x10e1c000, 0x7f1300, 0x10d1a090, 0x10e0c000)
        E:/GitHub/AIroot-JUS/src/jus/cn/airoot/util/server.go:575 +0xad
jus/cn/airoot/util.(*JusServer).(jus/cn/airoot/util.root)-fm(0x7f1300, 0x10d1a090, 0x10e0c000)
        E:/GitHub/AIroot-JUS/src/jus/cn/airoot/util/server.go:158 +0x38
net/http.HandlerFunc.ServeHTTP(0x10d74100, 0x7f1300, 0x10d1a090, 0x10e0c000)
        D:/go/src/net/http/server.go:1918 +0x34
net/http.(*ServeMux).ServeHTTP(0x10d6e520, 0x7f1300, 0x10d1a090, 0x10e0c000)
        D:/go/src/net/http/server.go:2254 +0xf0
net/http.serverHandler.ServeHTTP(0x10d70180, 0x7f1300, 0x10d1a090, 0x10e0c000)
        D:/go/src/net/http/server.go:2619 +0x8e
net/http.(*conn).serve(0x10cf0000, 0x7f1860, 0x10f74060)
        D:/go/src/net/http/server.go:1801 +0x5d1
created by net/http.(*Server).Serve
        D:/go/src/net/http/server.go:2720 +0x1f6
```

**Comment by uucckk** [comment]
此文提已经解决
