### ISSUE TITLE
新建WEB服务节点，如果没设定工程目录就启动，在访问的时候会报错

### ISSUE THREAD

**Issue by yeahpop** [uucckk/AIroot-JUS#8]
如题，我这么做后，直接敲网址，jus服务器就报这个错误，然后页面报无响应。虽然这是我的操作问题，但是建议添加上错误页，告诉使用者，你没有设置功能。这样体验能好一些。
```html
goroutine 19 [running]:
net/http.(*conn).serve.func1(0x1105c480)
        c:/d/go/src/net/http/server.go:1697 +0x9f
panic(0x665740, 0x814828)
        c:/d/go/src/runtime/panic.go:491 +0x1d0
jus/cn/airoot/util.(*JusServer).root(0x11092280, 0x7eb300, 0x1117c000, 0x11092300)
        c:/e/gowork.git/AIroot-JUS/src/jus/cn/airoot/util/server.go:555 +0x196
jus/cn/airoot/util.(*JusServer).(jus/cn/airoot/util.root)-fm(0x7eb300, 0x1117c000, 0x11092300)
        c:/e/gowork.git/AIroot-JUS/src/jus/cn/airoot/util/server.go:155 +0x38
net/http.HandlerFunc.ServeHTTP(0x11138038, 0x7eb300, 0x1117c000, 0x11092300)
        c:/d/go/src/net/http/server.go:1918 +0x34
net/http.(*ServeMux).ServeHTTP(0x1113c0a0, 0x7eb300, 0x1117c000, 0x11092300)
        c:/d/go/src/net/http/server.go:2254 +0xf0
net/http.serverHandler.ServeHTTP(0x1113a100, 0x7eb300, 0x1117c000, 0x11092300)
        c:/d/go/src/net/http/server.go:2619 +0x8e
net/http.(*conn).serve(0x1105c480, 0x7eb860, 0x110da800)
        c:/d/go/src/net/http/server.go:1801 +0x5d1
created by net/http.(*Server).Serve
        c:/d/go/src/net/http/server.go:2720 +0x1f6
```

**Comment by uucckk** [comment]
嗯嗯 是的，错误的原因是没有设置项目路径，那样服务器访问不到你要的页面，所以会报空指针错误。
确实如您所说，这样的响应确实让用户体验不好，我们正在加班筹备0.99版本的发布，
0.99版本是AIroot-JUS正式版发布前的beta版本。
我们现在全力jus的服务器的各方面能力。您提出的建议，我们会在0.99版本添加。

感谢您的支持!

**Comment by uucckk** [comment]
此问题在0.9.9 beta 02 已经更新过来
